### ISSUE TITLE
Adding coloured background for Tag Reference (Similar to bear theme)

### ISSUE THREAD

**Issue by krihna2498** [rcvd/logseq-quattro-theme#1]

**Comment by rcvd** [comment]
Add this on your `custom.css`-page below the ?`@import`-line

``` css
*:is(#main-content-container, #right-sidebar, .tippy-tooltip, .ls-card) a.tag:hover {
	background-color: 	var(--cl-chicago);
	border-top: 		transparent;
	border-right: 		transparent;
	border-bottom: 		transparent;
	border-left: 		transparent;
	color: 			var(--cl-white);
}

*:is(#main-content-container, #right-sidebar, .tippy-tooltip, .ls-card) a.tag {
	background-color: 	var(--cl-chicago);
	border-top: 		transparent;
	border-right: 		transparent;
	border-bottom: 		transparent;
	border-left: 		transparent;
	color: 			var(--cl-white);
	padding-left: 10px;
	padding-right: 10px;
}
```
